apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-1hb6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-dockerfile-empty-private-1hb6
    app.kubernetes.io/part-of: mc-golang-without
  name: devfile-sample-go-basic-dockerfile-empty-private-1hb6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-1hb6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-1hb6
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ohge-tenant/mc-golang-without/devfile-sample-go-basic-dockerfile-empty-private-1hb6@sha256:39b86f033cfe688ee5723833c2bee656c4661754a4bc04ab495ba3942727ca89
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
